### ISSUE TITLE
id values

### ISSUE THREAD

**Issue by echo66** [meteor-shuttle/ref#1]
Greetings!

You should allow Ref.id to be an instance of Meteor.Collection.ObjectID or a String. After all, Meteor.Collection.ObjectID is the object id type in MongoDB, AFAIK.

**Comment by ivansglazunov** [comment]
[SimpleSchema](https://github.com/aldeed/meteor-simple-schema) is does not support multiple typing.
I see only one solution. Manual redefine the schema. This makes it impossible to work with the [AutoForm](https://github.com/aldeed/meteor-autoform/).

``` js
new SimpleSchema({
    _source: {
      type: Object,
      custom: function() {
         if (!(typeof(this.value.id) == 'object' && this.value.id instanceof Meteor.ObjectID) || !(typeof(this.value.id) == 'string')) return 'notAllowed';
         if (typeof(this.value.collection) != 'string') return 'notAllowed';
      }
   }
});
```

**Comment by ivansglazunov** [comment]
I do not like this solution, but i just do not see other solutions.
In Meteor, [Mongo.Collection](http://docs.meteor.com/#/full/mongo_collection) construct by default with the string id.

**Comment by ivansglazunov** [comment]
What do you think is abandon the ability to control the auto forms for solution with objectId? Or is there another solution?

**Comment by konard** [comment]
Sound like we should make Schema that allow multiple / alternative typing. It is also known as sum type (https://en.wikipedia.org/wiki/Tagged_union , https://en.wikipedia.org/wiki/Algebraic_data_type).

**Comment by ivansglazunov** [comment]
As planned SimpleSchema(s) should have one type, for easy AutoForm(s).

**Comment by ivansglazunov** [comment]
Is possible to add an additional field `type` to the ref. 
For the conversion step function `Ref`:

``` js
{ collection: 'col', id: '123', type: 'ObjectID' }
// to
ObjectID("123")
```

However, this would mean that unprocessed objects can not be used without conversion.

**Comment by ivansglazunov** [comment]
It's ugly but it is possible. Need to think.

**Comment by ivansglazunov** [comment]
#2 Solved.
